import type { Metadata } from "next";
import { Khand } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";

const khand = Khand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-khand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${khand.className} touch-manipulation  text-black`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
