import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { khand } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${khand.className} touch-manipulation  text-black  `}
        style={{ backgroundColor: "#ffffff" }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
